<?php
//Copyright (c) 2012 Rubén Domínguez
//  
//This file is part of phpPMS.
//
//phpPMS is free software: you can redistribute it and/or modify
//it under the terms of the GNU General Public License as published by
//the Free Software Foundation, either version 3 of the License, or
//(at your option) any later version.
//
//phpPMS is distributed in the hope that it will be useful,
//but WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//GNU General Public License for more details.
//
//You should have received a copy of the GNU General Public License
//along with Foobar.  If not, see <http://www.gnu.org/licenses/>.


/**
 * Constants
 *
 * @author nuxsmin
 * @version 0.9b
 * @link http://www.cygnux.org/phppms
 */

define("PROJECT_VERSION","0.10");
define("PROJECT_NAME","phpPMS (basado en phpPasswordManager)");
define("PROJECT_COPYRIGHT","© 2012");
define("PROJECT_AUTHOR","rdb");
define("PROJECT_AUTHOR_EMAIL","rdb@mpsistemas.es");
define("PROJECT_HP_SF","http://sourceforge.net/projects/phppassmanager");

//define("HTML_HEADER","phpPasswordManager");
//define("HTML_TITLE","phpPasswordManager");
//define("HTML_HEADER","SGC - Sistema de Gestión de Claves");
define("HTML_HEADER","PMS - Password Management System");
//define("HTML_TITLE","SGC - Sistema de Gestión de Claves");
define("HTML_TITLE","PMS - Password Management System");
?>
